# Generated by Django 5.1.4 on 2025-05-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
