# Generated by Django 5.1.4 on 2025-05-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_productmodel_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='description',
        ),
    ]
